apiVersion: v1
kind: Service
metadata:
  name: kactivator
spec:
  ports:
  - name: grpc 
    port: 6100
    targetPort: 6100
  selector:
    app: kactivator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kactivator
spec:
  replicas: 1
  template:
    metadata:
      name: kactivator
      labels:
        app: kactivator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: kactivator-adapter
        image: registry.eu-gb.bluemix.net/hrl-istio/kactivator-adapter
        imagePullPolicy: Always
        args:
        - "6100"
        env:
        - name: AUTOSCALER_ENDPOINT
          value: "ws://autoscaler.knative-serving.svc.cluster.local:8080"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
